version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/a.sql
      - ./sql/store_procedures.sql:/docker-entrypoint-initdb.d/b.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/c.sql

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - backend-service

  backend-service:
    image: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - mysql

volumes:
  db:
    driver: local
