version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

volumes:
  db:
    driver: local