services:
  ecommerce-v1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5156:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true