services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/a.sql
      - ./sql/store_procedures.sql:/docker-entrypoint-initdb.d/b.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/c.sql
    networks:
        - ecommerce-network
  ecommerce-v2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5157:8080"
    networks:
        - ecommerce-network

volumes:
  db:
    driver: local

networks:
  ecommerce-network:
    external: true